management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.springframework: INFO
    io.pivotal.inventory: DEBUG

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5433/eCommerce-inventory
    username: inventory-user
    password: inventory123
  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc.lob.non_contextual_creation: true
    hibernate:
      ddl-auto: update
    show-sql: false

---

spring:
  profiles: windows
  datasource:
    url: jdbc:postgresql://localhost:5432/eCommerce-inventory